repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: \.svg$
      - id: mixed-line-ending
        args: ["--fix=lf"]
      - id: check-json
      - id: check-toml
      - id: forbid-submodules
      - id: detect-private-key
      - id: detect-aws-credentials
        args: ["--allow-missing-credentials"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.10.10
    hooks:
      - id: uv-lock

  - repo: local
    hooks:
      - id: ty-check
        name: ty check
        entry: uv run --frozen ty check
        types_or: [python, pyi]
        language: system
        pass_filenames: false
