"""Generate the API reference pages and nav from the package module tree.

Discovers the public top-level modules of ``timenet`` and ``timenet_connectors``,
writes one mkdocstrings stub per module into ``docs/api/``, regenerates the API
Reference landing page, and rewrites the marked ``api-nav`` region of
``zensical.toml`` so the sidebar always matches the generated pages.

Adding a new public SDK module makes it appear automatically; only genuinely
internal surfaces are dropped via ``EXCLUDE`` below. Reads source straight from
disk with :mod:`ast` (no imports, no network).

Run it before building the docs::

    uv run python scripts/gen_api_docs.py

Output goes to ``docs/api/`` (git-ignored; regenerated at build time).
"""

from __future__ import annotations

import ast
from dataclasses import dataclass
from pathlib import Path
import re


REPO_ROOT = Path(__file__).resolve().parent.parent
CONFIG_FILE = REPO_ROOT / "zensical.toml"
OUTPUT_DIR = REPO_ROOT / "docs" / "api"

# The two workspace packages and their importable roots on disk.
PACKAGE_ROOTS = {
    "timenet": REPO_ROOT / "packages" / "timenet" / "src" / "timenet",
    "timenet_connectors": REPO_ROOT / "packages" / "timenet-connectors" / "src" / "timenet_connectors",
}

# Public top-level modules that are intentionally NOT part of the documented API
# surface. Discovery picks up every other non-underscore top-level module on its
# own, so only genuinely internal surfaces need listing here.
EXCLUDE = {
    "timenet.cli",  # console-script plumbing (Typer app), not a code API
    "timenet.cache",  # cache-inspection helper
    "timenet.refs",  # internal org/id@version parser
    "timenet.torch",  # optional torch adapter (covered in the guide)
    "timenet.schemas",  # packaged JSON-Schema data, not code
    "timenet.testing",  # test-support helpers shipped in src
    "timenet_connectors.builder",  # producer CLI entry point
    "timenet_connectors.datasets",  # dynamic connector plugins, discovered by id
}

# Comment markers in zensical.toml delimiting the nav region this script rewrites.
NAV_BEGIN = "# >>> api-nav: generated by scripts/gen_api_docs.py — do not edit >>>"
NAV_END = "# <<< api-nav <<<"

# Reduce Sphinx-style cross-reference roles (:class:`Foo`) to plain code spans.
_RST_ROLE = re.compile(r":[a-z:]+:`~?([^`]+)`")


@dataclass(frozen=True)
class ApiModule:
    """One module to document.

    Attributes:
        dotted: Importable dotted path, e.g. ``timenet.registry``.
        slug: Output filename stem under ``docs/api/`` (the last path component).
        summary: Cleaned first line of the module docstring, or ``""``.
        show_submodules: Render submodules recursively (packages without ``__all__``).
    """

    dotted: str
    slug: str
    summary: str
    show_submodules: bool


def _clean_summary(docstring: str | None) -> str:
    """Reduce a docstring to a single clean summary line.

    Args:
        docstring: The raw module docstring, or ``None``.

    Returns:
        The first line with Sphinx roles turned into code spans, or ``""``.
    """
    lines = (docstring or "").strip().splitlines()
    if not lines:
        return ""
    return _RST_ROLE.sub(r"`\1`", lines[0].strip())


def _module_summary(source: Path) -> str:
    """Return the cleaned summary line of a module or package ``__init__``.

    Args:
        source: The module ``.py`` file or a package ``__init__.py``.

    Returns:
        The cleaned first docstring line, or ``""`` if the module has no docstring.
    """
    tree = ast.parse(source.read_text(encoding="utf-8", errors="replace"))
    return _clean_summary(ast.get_docstring(tree))


def _has_dunder_all(init_file: Path) -> bool:
    """Whether a package ``__init__.py`` assigns ``__all__`` at module level.

    Args:
        init_file: Path to the package's ``__init__.py``.

    Returns:
        True if ``__all__`` is assigned, else False.
    """
    tree = ast.parse(init_file.read_text(encoding="utf-8", errors="replace"))
    for node in tree.body:
        if isinstance(node, ast.Assign):
            targets = node.targets
        elif isinstance(node, ast.AnnAssign):
            targets = [node.target]
        else:
            continue
        if any(isinstance(t, ast.Name) and t.id == "__all__" for t in targets):
            return True
    return False


def _discover(package: str, root: Path) -> list[ApiModule]:
    """Discover the documented top-level modules of one package.

    Args:
        package: Import name of the package root (e.g. ``timenet``).
        root: Filesystem path to the package's importable directory.

    Returns:
        The modules to document, sorted by dotted path.
    """
    modules: list[ApiModule] = []
    for child in sorted(root.iterdir()):
        name = child.stem if child.suffix == ".py" else child.name
        # Document only importable modules/packages: a leading underscore is private,
        # and a non-identifier name is not importable. This also keeps generated names
        # safe to interpolate into TOML/YAML (identifiers need no escaping).
        if name.startswith("_") or not name.isidentifier():
            continue
        is_package = child.is_dir() and any(child.glob("*.py"))
        is_module = child.is_file() and child.suffix == ".py"
        if not (is_package or is_module):
            continue
        dotted = f"{package}.{name}"
        if dotted in EXCLUDE:
            continue
        if is_package:
            init_file = child / "__init__.py"
            # A package that builds a public API via __all__ is documented at the
            # package level; one that doesn't keeps its surface in submodules, so
            # render them recursively instead of an empty page.
            modules.append(ApiModule(dotted, name, _module_summary(init_file), not _has_dunder_all(init_file)))
        else:
            modules.append(ApiModule(dotted, name, _module_summary(child), False))
    return modules


def _write_stub(mod: ApiModule) -> None:
    """Write the mkdocstrings stub page for one module.

    Args:
        mod: The module to render.
    """
    desc = f"API reference for {mod.dotted}: {mod.summary}" if mod.summary else f"API reference for {mod.dotted}."
    lines = ["---", f'description: "{_yaml_escape(desc)}"', "---", "", f"::: {mod.dotted}"]
    if mod.show_submodules:
        lines += ["    options:", "      show_submodules: true"]
    (OUTPUT_DIR / f"{mod.slug}.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def _yaml_escape(text: str) -> str:
    """Escape a string for a double-quoted YAML scalar.

    Args:
        text: The raw string.

    Returns:
        The string with backslashes and double quotes escaped.
    """
    return text.replace("\\", "\\\\").replace('"', '\\"')


_INDEX_HEADER = """\
---
description: "Auto-generated API reference for the timenet and timenet-connectors packages."
---

# API Reference

Generated from the source docstrings. For narrative docs with examples, see the
[Guide](../architecture.md) and [Reference](../types.md) sections; the pages here are the
exhaustive symbol listing.
"""


def _write_index(by_package: dict[str, list[ApiModule]]) -> None:
    """Write the API Reference landing page listing every documented module.

    Args:
        by_package: Documented modules grouped by package root name.
    """
    parts = [_INDEX_HEADER]
    for package, mods in by_package.items():
        parts.append(f"## `{package}`\n")
        for mod in mods:
            bullet = f"- [`{mod.dotted}`]({mod.slug}.md)"
            if mod.summary:
                bullet += f" — {mod.summary}"
            parts.append(bullet)
        parts.append("")
    (OUTPUT_DIR / "index.md").write_text("\n".join(parts).rstrip() + "\n", encoding="utf-8")


def _nav_line(by_package: dict[str, list[ApiModule]]) -> str:
    """Build the single-line 'API Reference' nav entry for zensical.toml.

    Args:
        by_package: Documented modules grouped by package root name.

    Returns:
        A TOML inline-table array line (without indentation).
    """
    items = ['{ "Overview" = "api/index.md" }']
    for mods in by_package.values():
        items += [f'{{ "{mod.dotted}" = "api/{mod.slug}.md" }}' for mod in mods]
    return '{ "API Reference" = [' + ", ".join(items) + "] },"


def _rewrite_nav(nav_line: str) -> None:
    """Replace the marked api-nav region of zensical.toml in place.

    Args:
        nav_line: The generated 'API Reference' nav line to inject.

    Raises:
        SystemExit: If the marker region is missing or duplicated.
    """
    text = CONFIG_FILE.read_text(encoding="utf-8")
    pattern = re.compile(
        r"(?P<indent>[ \t]*)" + re.escape(NAV_BEGIN) + r"\n.*?\n[ \t]*" + re.escape(NAV_END),
        re.DOTALL,
    )

    def _sub(match: re.Match[str]) -> str:
        indent = match.group("indent")
        return f"{indent}{NAV_BEGIN}\n{indent}{nav_line}\n{indent}{NAV_END}"

    new_text, count = pattern.subn(_sub, text)
    if count != 1:
        raise SystemExit(f"api-nav markers not found (or duplicated) in {CONFIG_FILE.name}")
    if new_text != text:
        CONFIG_FILE.write_text(new_text, encoding="utf-8")


def main() -> None:
    """Generate the API pages and landing page, and rewrite the nav region.

    Raises:
        SystemExit: On a slug collision or a missing nav marker region.
    """
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    by_package = {pkg: _discover(pkg, root) for pkg, root in PACKAGE_ROOTS.items()}
    all_mods = [mod for mods in by_package.values() for mod in mods]

    # "index" is reserved for the landing page written by _write_index below.
    slugs: dict[str, str] = {"index": "(API index landing page)"}
    for mod in all_mods:
        if mod.slug in slugs:
            raise SystemExit(f"slug collision: {mod.dotted} and {slugs[mod.slug]} both map to {mod.slug}.md")
        slugs[mod.slug] = mod.dotted

    # Drop stale stubs left by a previous run with a different module set.
    for stale in OUTPUT_DIR.glob("*.md"):
        if stale.name != "index.md" and stale.stem not in slugs:
            stale.unlink()

    for mod in all_mods:
        _write_stub(mod)
    _write_index(by_package)
    _rewrite_nav(_nav_line(by_package))
    print(f"Generated {len(all_mods)} API pages + index; rewrote api-nav in {CONFIG_FILE.name}")


if __name__ == "__main__":
    main()
